export const OFFER_LIST_REQUEST = 'OFFER_LIST_REQUEST';
export const OFFER_LIST_SUCCESS = 'OFFER_LIST_SUCCESS';
export const OFFER_LIST_FAIL = 'OFFER_LIST_FAIL';

export const OFFER_DETAILS_REQUEST = 'OFFER_DETAILS_REQUEST';
export const OFFER_DETAILS_SUCCESS = 'OFFER_DETAILS_SUCCESS';
export const OFFER_DETAILS_FAIL = 'OFFER_DETAILS_FAIL';

export const OFFER_SAVE_REQUEST = 'OFFER_SAVE_REQUEST';
export const OFFER_SAVE_SUCCESS = 'OFFER_SAVE_SUCCESS';
export const OFFER_SAVE_FAIL = 'OFFER_SAVE_FAIL';

export const OFFER_DELETE_REQUEST = 'OFFER_DELETE_REQUEST';
export const OFFER_DELETE_SUCCESS = 'OFFER_DELETE_SUCCESS';
export const OFFER_DELETE_FAIL = 'OFFER_DELETE_FAIL';