export default  {
    products:[
        {
        _id:'1',
        name:'Slim Shirt',
        category: 'Shirts',
        image:'/img/d1.jpg',
        price: 60,
        brand:'Nike',
        rating:4.5,
        numReviews: 10,
        countInStock: 5,
    },
    {   
        _id:'2',
        name:'Slim Shirt',
        category:'shirts',
        image:'/img/d1.jpg',
        price: 60,
        brand:'Nike',
        rating:4.3,
        numReviews: 5,
        countInStock: 9,
    },
    {   
        _id:'3',
        name:'Fti Shirt',
        image:'/img/d1.jpg',
        price: 60,
        brand:'Nike',
        rating:3.5,
        numReviews: 8,
        countInStock: 6,
    },
    {
        _id:'4',
        name:'Slim Shirt',
        category:'shirts',
        image:'/img/d1.jpg',
        price: 60,
        brand:'Nike',
        rating:4.3,
        numReviews: 5,
        countInStock: 10,
    },
    {
        _id:'5',
        name:'Slim Shirt',
        category:'shirts',
        image:'/img/fondo.jpg',
        price: 60,
        brand:'Nike',
        rating:4.3,
        numReviews: 5,
        countInStock: 1,
    },
    
]
}